### ISSUE TITLE
Set common labels when creating objects 

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/operator-rs#99] opened 2021-04-20 15:54 UTC
We have a set of common labels [1] that we want to use for objects in Kubernetes. Some of these will have to be set by the operator as the necessary information is only known there.
But for some labels this could be moved to the operator framework as well.

For example the 'managed-by' label could be filled by adding a function to the operator / crd that returns a string to be put here, which would then be called by the framework.

[1]https://github.com/stackabletech/operator-rs/blob/main/src/labels.rs

**Comment by lfrancke** [comment] 2021-05-14 07:25
Some of this functionality already exists but it can probably be improved.

**Comment by lfrancke** [comment] 2021-05-14 07:26
This seems like a duplicate of #94 ?

**Comment by lfrancke** [comment] 2021-06-18 07:05
Closed as duplicate

**Closed by lfrancke** 2021-06-18 07:05 UTC
Labels: priority/high, type/enhancement
