### ISSUE TITLE
Add functionality to set required labels to build_metadata function

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/operator-rs#94] opened 2021-04-08 14:03 UTC
We have agreed to use a set of default labels, as per what [Kubernetes best practice expects](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). 

> app.kubernetes.io/name	The name of the application	
> app.kubernetes.io/instance	A unique name identifying the instance of an application	
> app.kubernetes.io/version	The current version of the application (e.g., a semantic version, revision hash, etc.)
> app.kubernetes.io/component	The component within the architecture
> app.kubernetes.io/part-of	The name of a higher level application this one is part of
> app.kubernetes.io/managed-by	The tool being used to manage the operation of an application

It would make sense to have these supported by build_metadata in some form.

**Comment by lfrancke** [comment] 2021-05-14 07:27
This seems like a duplicate of #99

**Comment by lfrancke** [comment] 2021-06-07 10:00
This will be worked on as part of the `pod_builder` branch by @razvan

**Closed** 2021-07-02 13:36 UTC
Labels: priority/high, type/enhancement
